all:	beta.html \
	cmos.html \
	computation.html \
	digital.html \
	gates.html \
	info.html \
	logic.html \
	sequential.html \
	machinelang.html \
	memhierarchy.html \
	caches.html \
	os.html \
	pipeline.html \
	pipelinedbeta.html \
	procedures.html \
	progmach.html \
	realtime.html \
	semaphores.html \
	fsm.html \
	synchronization.html \
	vm.html \

ward_doit:	all

beta.html: beta.xdoc
	python tutprobs.py beta

caches.html: caches.xdoc
	python tutprobs.py caches

cmos.html: cmos.xdoc
	python tutprobs.py cmos

computation.html: computation.xdoc
	python tutprobs.py computation

digital.html: digital.xdoc
	python tutprobs.py digital

gates.html: gates.xdoc
	python tutprobs.py gates

info.html: info.xdoc
	python tutprobs.py info

logic.html: logic.xdoc
	python tutprobs.py logic

sequential.html: sequential.xdoc
	python tutprobs.py sequential

machinelang.html: machinelang.xdoc
	python tutprobs.py machinelang

memhierarchy.html: memhierarchy.xdoc
	python tutprobs.py memhierarchy

os.html: os.xdoc
	python tutprobs.py os

pipeline.html: pipeline.xdoc
	python tutprobs.py pipeline

pipelinedbeta.html: pipelinedbeta.xdoc
	python tutprobs.py pipelinedbeta

procedures.html: procedures.xdoc
	python tutprobs.py procedures

progmach.html: progmach.xdoc
	python tutprobs.py progmach

realtime.html: realtime.xdoc
	python tutprobs.py realtime

semaphores.html: semaphores.xdoc
	python tutprobs.py semaphores

fsm.html: fsm.xdoc
	python tutprobs.py fsm

synchronization.html: synchronization.xdoc
	python tutprobs.py synchronization

vm.html: vm.xdoc
	python tutprobs.py vm
